### ISSUE TITLE
Account Activation

### ISSUE THREAD

**Issue by dcbaldwin1** [brashrebel/wordcrash-theme#10]
The first activation email states 'After you activate, you will receive _another email_ with your login.'

I never received another email with my login.

**Comment by brashrebel** [comment]
Good point! I know that text can be filtered so we should add a function in the functionality plugin we're using. @dcbaldwin1 do you know how to and have the time to do it?

**Comment by dcbaldwin1** [comment]
Not sure but I'd love to take a look and mess around on a dev site. Do you have a dev site or will you have a repo? I could donate a hosting account if needed but it surely isn't the best for WordPress (plesk on mediatemple).

**Comment by dcbaldwin1** [comment]
On mobile sorry I see the master branch and the theme code

**Comment by dcbaldwin1** [comment]
A wp-content/plugins plugin? Yeah I think I could help but not for a week or so - I'm catching from knee surgery.

**Comment by brashrebel** [comment]
If you have time to get to it, here's the repo where we'd like to add such a function:

https://github.com/brashrebel/wordcrash-functionality

**Comment by dcbaldwin1** [comment]
I should be able to look in the next week.

**Comment by dcbaldwin1** [comment]
I have a local install of WordPress multisite and a couple sites are set up (one being wordcrash) and running smoothly, except for emails. I'm using MAMP. I can't get any emails to send at all. I don't have MAMP Pro either, which I may end up having to get. I've tried WP SMTP Mail and some other MAMP (free) work arounds to no avail.

Have you ever gotten emails working locally with multisite?

**Comment by brashrebel** [comment]
@dcbaldwin1 yes, as I've had intermittent problems to. Though they all went away as soon as I started using wpMandrill. Network activate that and setup a free account with Mandrill and you'll be all set.

**Comment by dcbaldwin1** [comment]
Favorited wpMandrill. Thanks for the pointer.

**Comment by joelworsham** [comment]
This issue was moved to brashrebel/wordcrash-functionality#4
