### ISSUE TITLE
Activation Email

### ISSUE THREAD

**Issue by dcbaldwin1** [brashrebel/wordcrash-theme#9]
Could add some more info here...

I was also a bit confused when the email subject was 'Real Big Marketing sites'

**Comment by brashrebel** [comment]
Related to #3 and #4. Definitely need to change who the welcome email is from and add more text. @dcbaldwin1 do you have experience doing this on a multisite network?

**Comment by dcbaldwin1** [comment]
Well I have experience with both welcome emails and multisite, but separately.

How does multisite apply to wordcrash.net?

**Comment by brashrebel** [comment]
This site is currently on a multisite network. Maybe at some point we'll move it off of one but that's where it sits right now. So I'd love to manipulate the activation email, there are just nuances to that when on a multisite.

**Comment by dcbaldwin1** [comment]
I see. I'm definitely not aware of what to look out for on multisite, when filtering the activation email. Really wouldn't want to start hacking  unless I was on a dev/staging server.

I could help migrate to a regular WordPress install at some point in the future.

Derek

**Comment by brashrebel** [comment]
@dcbaldwin1 we might consider that at some point. And we have a staging site for this too that we can test on.

**Comment by joelworsham** [comment]
This issue was moved to brashrebel/wordcrash-functionality#5
